### ISSUE TITLE
Build-Vultr-vps-on-Shadowsocks - StandHR Blog

### ISSUE THREAD

**Issue by StandHR** [StandHR/Gitment#10]
https://standhr.github.io/2017/12/15/Build-Vultr-vps-on-Shadowsocks/

**Comment by lzc5927** [comment]
那个一键安装脚本可真是好用啊……然后请问大佬“2>&1 | tee shadowsocks.log”是做什么用的啊

**Comment by StandHR** [comment]
@lzc5927 shell脚本语言，好像是输出重定向。
